import type {
  Review,
  MockImage,
  RatingDistribution,
} from "./ReviewSection.types";

export const REVIEWS: Review[] = [
  {
    id: 1,
    name: "Sarah M.",
    initials: "SM",
    rating: 5,
    title: "Absolutely love this product!",
    body: "I've been using this for 3 weeks and it's completely transformed my routine. The quality is outstanding and it arrived perfectly packaged. Will definitely be ordering again.",
    date: "Feb 18, 2026",
    verified: true,
    helpful: 24,
    hasImages: true,
  },
  {
    id: 2,
    name: "Daniel K.",
    initials: "DK",
    rating: 5,
    title: "Exceeded my expectations",
    body: "Ordered this as a gift and the recipient was thrilled. Fast shipping, beautiful presentation, and the product itself is top-notch. Highly recommend for anyone on the fence.",
    date: "Feb 10, 2026",
    verified: true,
    helpful: 17,
    hasImages: false,
  },
  {
    id: 3,
    name: "Rachel T.",
    initials: "RT",
    rating: 4,
    title: "Great quality, minor packaging issue",
    body: "The product itself is excellent — exactly as described. My only gripe is the outer box arrived slightly dented. The contents were fine though. Customer support was super responsive when I reached out.",
    date: "Jan 29, 2026",
    verified: true,
    helpful: 9,
    hasImages: false,
  },
  {
    id: 4,
    name: "Marcus B.",
    initials: "MB",
    rating: 5,
    title: "Best purchase I've made this year",
    body: "Don't hesitate, just buy it. I was skeptical about the price point but it's absolutely worth every cent. Premium feel, works exactly as advertised. Already recommended to three friends.",
    date: "Jan 22, 2026",
    verified: false,
    helpful: 31,
    hasImages: true,
  },
  {
    id: 5,
    name: "Priya S.",
    initials: "PS",
    rating: 3,
    title: "Good but room for improvement",
    body: "Works well for what it is, but I expected a bit more based on the description. The core functionality is solid. I've seen better finishes at this price range, but overall I don't regret the purchase.",
    date: "Jan 14, 2026",
    verified: true,
    helpful: 5,
    hasImages: false,
  },
  {
    id: 6,
    name: "James O.",
    initials: "JO",
    rating: 4,
    title: "Solid product, fast delivery",
    body: "Really impressed with the build quality. Delivery was faster than expected and the packaging was great. Minor learning curve but once you get the hang of it, it's seamless.",
    date: "Jan 5, 2026",
    verified: true,
    helpful: 12,
    hasImages: false,
  },
  {
    id: 7,
    name: "Aisha N.",
    initials: "AN",
    rating: 5,
    title: "Genuinely impressed",
    body: "I've bought similar products before but nothing compares. The attention to detail is evident from the moment you open the box. My whole family has commented on it. Five stars without hesitation.",
    date: "Dec 30, 2025",
    verified: true,
    helpful: 19,
    hasImages: true,
  },
  {
    id: 8,
    name: "Tom W.",
    initials: "TW",
    rating: 4,
    title: "Really good, small gripe with instructions",
    body: "The product itself is fantastic — premium materials and exactly the right size. The setup instructions could be clearer though. Took me a bit longer than it should have. Once running, absolutely flawless.",
    date: "Dec 21, 2025",
    verified: true,
    helpful: 8,
    hasImages: false,
  },
  {
    id: 9,
    name: "Elena V.",
    initials: "EV",
    rating: 5,
    title: "Worth every penny",
    body: "Deliberated for weeks before buying and I wish I hadn't waited. The quality is leagues above what I had before. Shipping was lightning fast and it arrived in perfect condition. Genuinely couldn't be happier.",
    date: "Dec 15, 2025",
    verified: true,
    helpful: 22,
    hasImages: false,
  },
  {
    id: 10,
    name: "Chris L.",
    initials: "CL",
    rating: 3,
    title: "Decent but not perfect",
    body: "Does what it says on the tin, but a couple of the finishing touches feel a bit rushed for the price point. I'd still recommend it — the core experience is solid — but there's room to polish.",
    date: "Dec 9, 2025",
    verified: false,
    helpful: 6,
    hasImages: false,
  },
  {
    id: 11,
    name: "Fatima H.",
    initials: "FH",
    rating: 5,
    title: "Stunning — better than photos",
    body: "Photos don't do it justice. In person it looks and feels incredibly premium. I've had multiple friends ask where I got it. Customer service was also super helpful when I had a pre-purchase question.",
    date: "Dec 2, 2025",
    verified: true,
    helpful: 28,
    hasImages: true,
  },
  {
    id: 12,
    name: "Oliver P.",
    initials: "OP",
    rating: 4,
    title: "Great everyday item",
    body: "Using it daily and it's held up brilliantly. No wear or issues after two months of heavy use. The color is exactly as shown. Would have given 5 stars if delivery wasn't a day late — minor gripe.",
    date: "Nov 25, 2025",
    verified: true,
    helpful: 14,
    hasImages: false,
  },
  {
    id: 13,
    name: "Mei L.",
    initials: "ML",
    rating: 5,
    title: "Second purchase — just as good",
    body: "I bought one last year and gifted it, then immediately missed having it myself. This second purchase is just as good in every way. Consistency matters and this brand delivers every time.",
    date: "Nov 18, 2025",
    verified: true,
    helpful: 33,
    hasImages: false,
  },
  {
    id: 14,
    name: "Ryan G.",
    initials: "RG",
    rating: 2,
    title: "Not quite what I expected",
    body: "A bit disappointed honestly. The product works but feels cheaper in person than it looks in the photos. For this price I expected better. Customer support was polite but couldn't resolve my concern.",
    date: "Nov 10, 2025",
    verified: true,
    helpful: 3,
    hasImages: false,
  },
  {
    id: 15,
    name: "Nadia R.",
    initials: "NR",
    rating: 5,
    title: "Obsessed with this",
    body: "Ordered on a whim and now I can't imagine not having it. The design is sleek, it works perfectly, and after a month of use it still looks brand new. One of those purchases you're just glad you made.",
    date: "Nov 3, 2025",
    verified: true,
    helpful: 41,
    hasImages: true,
  },
  {
    id: 16,
    name: "Ben F.",
    initials: "BF",
    rating: 4,
    title: "Solid all-rounder",
    body: "Not the flashiest option out there but easily the most reliable I've tried. Does exactly what it promises with zero fuss. Build quality is excellent and it came very well packaged. Happy customer.",
    date: "Oct 27, 2025",
    verified: false,
    helpful: 10,
    hasImages: false,
  },
];

export const RATING_DISTRIBUTION: RatingDistribution = {
  5: 68,
  4: 18,
  3: 8,
  2: 4,
  1: 2,
};

export const MOCK_IMAGES: MockImage[] = [
  { bg: "#edf5ea", stroke: "#2a7a6f" },
  { bg: "#fef9ec", stroke: "#d4a030" },
];

export const HIGHLIGHT_TAGS: [string, number][] = [
  ["Quality", 94],
  ["Fast shipping", 89],
  ["True to size", 82],
  ["Great value", 76],
];

export const AVATAR_HUES = [168, 195, 220, 145, 260, 30];

export const SORT_OPTIONS: { key: string; label: string }[] = [
  { key: "recent", label: "Recent" },
  { key: "highest", label: "Top rated" },
  { key: "helpful", label: "Helpful" },
];

export const FILTER_OPTIONS = ["all", "5", "4", "3"] as const;
