import type { Slide } from "./UGCCarousel.types";

export const SLIDES: Slide[] = [
  {
    id: 1,
    type: "video",
    vimeoId: "1171537684",
    vimeoHash: "35507847e2",
    username: "@sarahstyle",
    platform: "instagram",
  },
  {
    id: 2,
    type: "placeholder",
    bg: ["#dceefb", "#b8d9f5"],
    accent: "#4a90c4",
    emoji: "\u{1F64C}",
    label: "Game changer for real \u{1F525}",
    username: "@danielcooks",
    platform: "tiktok",
  },
  {
    id: 3,
    type: "video",
    vimeoId: "1171537667",
    username: "@racheltravels",
    platform: "instagram",
  },
  {
    id: 4,
    type: "placeholder",
    bg: ["#fce4ec", "#f8bbd0"],
    accent: "#c2607a",
    emoji: "\u{1F4AA}",
    label: "Best purchase this year \u{1F4AA}",
    username: "@marcuslifts",
    platform: "tiktok",
  },
  {
    id: 5,
    type: "placeholder",
    bg: ["#fff8e1", "#ffecb3"],
    accent: "#d4a030",
    emoji: "\u{2B50}",
    label: "Worth every penny \u{1F31F}",
    username: "@jamesoutdoors",
    platform: "instagram",
  },
  {
    id: 6,
    type: "placeholder",
    bg: ["#edf5ea", "#b2d8d4"],
    accent: "#2a7a6f",
    emoji: "\u{1F60D}",
    label: "Obsessed with mine \u{2728}",
    username: "@priyabeauty",
    platform: "tiktok",
  },
];
